# Generated by Django 3.2.9 on 2021-11-30 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatehistory',
            name='user',
        ),
        migrations.AddField(
            model_name='updatehistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
